### ISSUE TITLE
Issue in Vuzix m300 device 

### ISSUE THREAD

**Issue by rohitup** [u-ryo/SharedEye#1]
Getting fatal exception after running the app in vuzix m300 device:
FATAL EXCEPTION: main
                                                                              Process: bz.mydns.walt.webrtc.sharedeye, PID: 7815
                                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{bz.mydns.walt.webrtc.sharedeye/bz.mydns.walt.webrtc.sharedeye.MainActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class org.xwalk.core.XWalkView
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                               Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class org.xwalk.core.XWalkView
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                                  at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393)
                                                                                  at android.app.Activity.setContentView(Activity.java:2174)
                                                                                  at bz.mydns.walt.webrtc.sharedeye.MainActivity.onCreate(MainActivity.kt:29)
                                                                                  at android.app.Activity.performCreate(Activity.java:6275)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                               Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class org.xwalk.core.XWalkView
                                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                  at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393) 
                                                                                  at android.app.Activity.setContentView(Activity.java:2174) 
                                                                                  at bz.mydns.walt.webrtc.sharedeye.MainActivity.onCreate(MainActivity.kt:29) 
                                                                                  at android.app.Activity.performCreate(Activity.java:6275) 
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                               Caused by: java.lang.reflect.InvocationTargetException
                                                                                  at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                  at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393) 
                                                                                  at android.app.Activity.setContentView(Activity.java:2174) 
                                                                                  at bz.mydns.walt.webrtc.sharedeye.MainActivity.onCreate(MainActivity.kt:29) 
                                                                                  at android.app.Activity.performCreate(Activity.java:6275) 
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                               Caused by: junit.framework.AssertionFailedError: Please have your activity extend XWalkActivity for shared mode
                                                                                  at junit.framework.Assert.fail(Assert.java:50)
                                                                                  at org.xwalk.core.XWalkCoreWrapper.initEmbeddedMode(XWalkCoreWrapper.java:245)
                                                                                  at org.xwalk.core.XWalkView.reflectionInit(XWalkView.java:1622)
                                                                                  at org.xwalk.core.XWalkView.<init>(XWalkView.java:239)

**Comment by u-ryo** [comment]
Thank you for reporting. I'm checking...

**Comment by u-ryo** [comment]
I added m300 branch.
Just updated CrossWalk (and abandoned m100 support).
Please try it and tell me the result.

**Comment by rohitup** [comment]
Thanks for the update but still I am getting the same error on runtime.

FATAL EXCEPTION: main
                                                 Process: bz.mydns.walt.webrtc.sharedeye, PID: 4589
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{bz.mydns.walt.webrtc.sharedeye/bz.mydns.walt.webrtc.sharedeye.MainActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class org.xwalk.core.XWalkView
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                  Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class org.xwalk.core.XWalkView
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                     at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393)
                                                     at android.app.Activity.setContentView(Activity.java:2174)
                                                     at bz.mydns.walt.webrtc.sharedeye.MainActivity.onCreate(MainActivity.kt:38)
                                                     at android.app.Activity.performCreate(Activity.java:6275)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                  Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class org.xwalk.core.XWalkView
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                     at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393) 
                                                     at android.app.Activity.setContentView(Activity.java:2174) 
                                                     at bz.mydns.walt.webrtc.sharedeye.MainActivity.onCreate(MainActivity.kt:38) 
                                                     at android.app.Activity.performCreate(Activity.java:6275) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                     at java.lang.reflect.Constructor.newInstance(Native Method)
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                     at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393) 
                                                     at android.app.Activity.setContentView(Activity.java:2174) 
                                                     at bz.mydns.walt.webrtc.sharedeye.MainActivity.onCreate(MainActivity.kt:38) 
                                                     at android.app.Activity.performCreate(Activity.java:6275) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                  Caused by: java.lang.RuntimeException: Please have your activity extend XWalkActivity for shared mode
                                                     at org.xwalk.core.XWalkCoreWrapper.initEmbeddedMode(XWalkCoreWrapper.java:214)
                                                     at org.xwalk.core.XWalkView.reflectionInit(XWalkView.java:2054)
                                                     at org.xwalk.core.XWalkView.<init>(XWalkView.java:299)

**Comment by u-ryo** [comment]
Thank you for trying and reporting again.
I'm checking...

**Comment by u-ryo** [comment]
I introduced onXWalkReady() in "m300" branch.
ref: https://lists.crosswalk-project.org/pipermail/crosswalk-help/2016-April/001907.html
Please try again on the "m300" branch.

**Comment by rohitup** [comment]
Thanks it's working now

**Comment by u-ryo** [comment]
Great.
Thank you for reporting and trying.
